export const Cities = [
{
  city: "Lille", 
  lat: "50.6278", 
  lng: "3.0583", 
  country: "France", 
  iso2: "FR", 
  admin_name: "Hauts-de-France", 
  capital: "admin", 
  population: "232787", 
  population_proper: "232787"
}, 
{
  city: "Reims", 
  lat: "49.2628", 
  lng: "4.0347", 
  country: "France", 
  iso2: "FR", 
  admin_name: "Grand Est", 
  capital: "minor", 
  population: "182460", 
  population_proper: "182211"
}, 
{
  city: "Saint-Étienne", 
  lat: "45.4347", 
  lng: "4.3903", 
  country: "France", 
  iso2: "FR", 
  admin_name: "Auvergne-Rhône-Alpes", 
  capital: "minor", 
  population: "172565", 
  population_proper: "172565"
}, 
{
  city: "Toulon", 
  lat: "43.1258", 
  lng: "5.9306", 
  country: "France", 
  iso2: "FR", 
  admin_name: "Provence-Alpes-Côte d’Azur", 
  capital: "minor", 
  population: "171953", 
  population_proper: "171953"
}, 
{
  city: "Dijon", 
  lat: "47.3167", 
  lng: "5.0167", 
  country: "France", 
  iso2: "FR", 
  admin_name: "Bourgogne-Franche-Comté", 
  capital: "admin", 
  population: "156920", 
  population_proper: "156854"
}, 
{
  city: "Angers", 
  lat: "47.4736", 
  lng: "-0.5542", 
  country: "France", 
  iso2: "FR", 
  admin_name: "Pays de la Loire", 
  capital: "minor", 
  population: "152960", 
  population_proper: "152960"
}, 
{
  city: "Nîmes", 
  lat: "43.8380", 
  lng: "4.3610", 
  country: "France", 
  iso2: "FR", 
  admin_name: "Occitanie", 
  capital: "minor", 
  population: "151001", 
  population_proper: "149633"
}, 
{
  city: "Villeurbanne", 
  lat: "45.7667", 
  lng: "4.8803", 
  country: "France", 
  iso2: "FR", 
  admin_name: "Auvergne-Rhône-Alpes", 
  capital: "", 
  population: "147712", 
  population_proper: "147712"
}, 
{
  city: "Clermont-Ferrand", 
  lat: "45.7831", 
  lng: "3.0824", 
  country: "France", 
  iso2: "FR", 
  admin_name: "Auvergne-Rhône-Alpes", 
  capital: "minor", 
  population: "143886", 
  population_proper: "143886"
}, 
{
  city: "Le Mans", 
  lat: "48.0077", 
  lng: "0.1984", 
  country: "France", 
  iso2: "FR", 
  admin_name: "Pays de la Loire", 
  capital: "minor", 
  population: "142946", 
  population_proper: "142946"
}, 
{
  city: "Aix-en-Provence", 
  lat: "43.5263", 
  lng: "5.4454", 
  country: "France", 
  iso2: "FR", 
  admin_name: "Provence-Alpes-Côte d’Azur", 
  capital: "minor", 
  population: "142482", 
  population_proper: "142482"
}, 
{
  city: "Amiens", 
  lat: "49.8920", 
  lng: "2.2990", 
  country: "France", 
  iso2: "FR", 
  admin_name: "Hauts-de-France", 
  capital: "minor", 
  population: "136105", 
  population_proper: "133891"
}, 
{
  city: "Tours", 
  lat: "47.2436", 
  lng: "0.6892", 
  country: "France", 
  iso2: "FR", 
  admin_name: "Centre-Val de Loire", 
  capital: "minor", 
  population: "135787", 
  population_proper: "135787"
}, 
{
  city: "Boulogne-sur-Mer", 
  lat: "50.7264", 
  lng: "1.6147", 
  country: "France", 
  iso2: "FR", 
  admin_name: "Hauts-de-France", 
  capital: "minor", 
  population: "133062", 
  population_proper: "40664"
}, 
{
  city: "Annecy", 
  lat: "45.9160", 
  lng: "6.1330", 
  country: "France", 
  iso2: "FR", 
  admin_name: "Auvergne-Rhône-Alpes", 
  capital: "minor", 
  population: "126924", 
  population_proper: "126924"
}, 
{
  city: "Perpignan", 
  lat: "42.6986", 
  lng: "2.8956", 
  country: "France", 
  iso2: "FR", 
  admin_name: "Occitanie", 
  capital: "minor", 
  population: "120158", 
  population_proper: "119188"
}, 
{
  city: "Boulogne-Billancourt", 
  lat: "48.8352", 
  lng: "2.2409", 
  country: "France", 
  iso2: "FR", 
  admin_name: "Île-de-France", 
  capital: "minor", 
  population: "120071", 
  population_proper: "120071"
}, 
{
  city: "Besançon", 
  lat: "47.2400", 
  lng: "6.0200", 
  country: "France", 
  iso2: "FR", 
  admin_name: "Bourgogne-Franche-Comté", 
  capital: "minor", 
  population: "115934", 
  population_proper: "115934"
}, ]
export const Pays = [ 
  {name: 'Afghanistan', code: 'AF'}, 
  {name: 'Åland Islands', code: 'AX'}, 
  {name: 'Albania', code: 'AL'}, 
  {name: 'Algeria', code: 'DZ'}, 
  {name: 'American Samoa', code: 'AS'}, 
  {name: 'AndorrA', code: 'AD'}, 
  {name: 'Angola', code: 'AO'}, 
  {name: 'Anguilla', code: 'AI'}, 
  {name: 'Benin', code: 'BJ'}, 
  {name: 'Bermuda', code: 'BM'}, 
  {name: 'Bhutan', code: 'BT'}, 
  {name: 'Bolivia', code: 'BO'}, 
  {name: 'Bosnia and Herzegovina', code: 'BA'}, 
  {name: 'Botswana', code: 'BW'}, 
  {name: 'Bouvet Island', code: 'BV'}, 
  {name: 'Brazil', code: 'BR'},]